void testPWMLocalReadWrite();                               
void testPWMRemoteReadWrite();                              
void testDOUTLocalReadWrite();                              
void testDOUTRemoteReadWrite();                             
void testDINLocalRead();                                    
void testDINRemoteRead();                                   
void testAINLocalRead();                                    
void testAINRemoteRead();                                   
void testServoLocalReadWrite();                             
void testServoRemoteReadWrite();                            
void multiServoTest();                                      
void pause(long mS);